GET https://powerful-coast-98110.herokuapp.com/api/persons
###
DELETE https://powerful-coast-98110.herokuapp.com/api/persons/2
###
POST https://powerful-coast-98110.herokuapp.com/api/persons
Content-Type: application/json

{
	"name": "Joe Shmoe",
	"number": "1-555-445-555"
}